apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-tier
  labels:
    app: microservices
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: front
  template:
    metadata:
      labels:
        app: microservices
        tier: front
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/mfth12/karsajobs-ui:latest
          env:
            - name: VUE_APP_BACKEND
              # DNS for service discovery
              # Naming pattern:
              #   IP address: <service_name>.<service_namespace>
              #   Port: needs to be extracted from SRV DNS record
              value: http://app-tier:$(APP_TIER_SERVICE_PORT)